import type {
  ChildViewProfile,
  OngoingCourse,
  RecommendedLesson,
  SubjectTechTree,
  ChildFriend,
  PraiseMessage,
} from './types';

export const CHILD_PROFILE_MOCK: ChildViewProfile = {
  id: 'child-1',
  nickname: '수학왕 민준',
  code: 'ABC123',
  representativeBadgeId: 'math-mental-calc-3',
  streak: 7,
  todayGoalMinutes: 60,
  todayStudiedMinutes: 35,
};

export const ONGOING_COURSES_MOCK: OngoingCourse[] = [
  {
    id: 'course-1',
    subject: '수학',
    title: '분수와 소수의 연산',
    tutorName: '수학 박사 알파',
    tutorEmoji: '🤖',
    progressPercent: 65,
    totalMinutes: 40,
    doneMinutes: 26,
    color: 'orange',
  },
  {
    id: 'course-2',
    subject: '음악',
    title: '음계와 리듬 익히기',
    tutorName: '음악 선생님 도레미',
    tutorEmoji: '🎵',
    progressPercent: 30,
    totalMinutes: 30,
    doneMinutes: 9,
    color: 'violet',
  },
  {
    id: 'course-3',
    subject: '국어',
    title: '독해력 향상 프로젝트',
    tutorName: '국어 선생님 한글이',
    tutorEmoji: '📖',
    progressPercent: 80,
    totalMinutes: 25,
    doneMinutes: 20,
    color: 'blue',
  },
];

export const RECOMMENDED_LESSONS_MOCK: RecommendedLesson[] = [
  {
    id: 'rec-1',
    subject: '수학',
    title: '암산 속도 올리기 특훈',
    reason: '최근 암산 능력이 상위 28%까지 올라왔어요! 조금만 더 하면 다음 뱃지를 딸 수 있어요.',
    tutorName: '수학 박사 알파',
    tutorEmoji: '🤖',
    durationMinutes: 15,
    color: 'orange',
  },
  {
    id: 'rec-2',
    subject: '음악',
    title: '절대음감 테스트 도전',
    reason: '음감 능력이 꾸준히 성장하고 있어요. 오늘 테스트로 실력을 확인해 봐요!',
    tutorName: '음악 선생님 도레미',
    tutorEmoji: '🎵',
    durationMinutes: 10,
    color: 'violet',
  },
];

export const SUBJECT_TECH_TREES_MOCK: SubjectTechTree[] = [
  {
    subject: '수학',
    subjectEmoji: '🔢',
    tutorName: '수학 박사 알파',
    tutorEmoji: '🤖',
    badges: [
      {
        id: 'math-mental-calc-1',
        subject: '수학',
        ability: '암산',
        level: 3,
        levelTitles: ['암산 입문', '머릿속에 계산기', '머리로 다해', '산술가', '암산 마스터'],
        topPercent: 28,
        acquired: true,
        needsReview: false,
        color: 'gold',
        emoji: '🧮',
      },
      {
        id: 'math-creative-1',
        subject: '수학',
        ability: '창의적 문제 해결',
        level: 2,
        levelTitles: ['호기심 탐험가', '창의적 사고자', '문제 해결사', '발명가', '창의 천재'],
        topPercent: 55,
        acquired: true,
        needsReview: false,
        color: 'blue',
        emoji: '💡',
      },
      {
        id: 'math-logic-1',
        subject: '수학',
        ability: '논리적 사고',
        level: 1,
        levelTitles: ['논리 입문', '패턴 발견자', '논리 탐정', '추론 전문가', '논리 마스터'],
        topPercent: 72,
        acquired: false,
        needsReview: false,
        color: 'green',
        emoji: '🔍',
      },
    ],
  },
  {
    subject: '음악',
    subjectEmoji: '🎵',
    tutorName: '음악 선생님 도레미',
    tutorEmoji: '🎵',
    badges: [
      {
        id: 'music-pitch-1',
        subject: '음악',
        ability: '음감',
        level: 2,
        levelTitles: ['음감 입문', '음감 소년/소녀', '음감 탐험가', '절대음감 후보', '절대음감'],
        topPercent: 42,
        acquired: true,
        needsReview: false,
        color: 'violet',
        emoji: '🎼',
      },
      {
        id: 'music-rhythm-1',
        subject: '음악',
        ability: '리듬감',
        level: 1,
        levelTitles: ['리듬 입문', '박자 맞추기', '리듬 마스터', '비트 메이커', '리듬의 신'],
        topPercent: 68,
        acquired: true,
        needsReview: true,
        color: 'rose',
        emoji: '🥁',
      },
    ],
  },
  {
    subject: '국어',
    subjectEmoji: '📖',
    tutorName: '국어 선생님 한글이',
    tutorEmoji: '📖',
    badges: [
      {
        id: 'korean-reading-1',
        subject: '국어',
        ability: '독해력',
        level: 3,
        levelTitles: ['독해 입문', '이야기 탐험가', '독해 전문가', '문학 감정가', '독서왕'],
        topPercent: 18,
        acquired: true,
        needsReview: false,
        color: 'blue',
        emoji: '📚',
      },
      {
        id: 'korean-writing-1',
        subject: '국어',
        ability: '글쓰기',
        level: 2,
        levelTitles: ['글쓰기 입문', '이야기꾼', '작가 지망생', '스토리텔러', '문장의 달인'],
        topPercent: 35,
        acquired: true,
        needsReview: false,
        color: 'green',
        emoji: '✏️',
      },
    ],
  },
];

export const FRIENDS_MOCK: ChildFriend[] = [
  {
    id: 'friend-1',
    nickname: '피아노 천재 지우',
    representativeBadgeId: 'music-pitch-2',
    representativeBadgeEmoji: '🎼',
    representativeBadgeTitle: '음감 탐험가',
    studiedToday: true,
  },
  {
    id: 'friend-2',
    nickname: '독서왕 서연',
    representativeBadgeId: 'korean-reading-3',
    representativeBadgeEmoji: '📚',
    representativeBadgeTitle: '독해 전문가',
    studiedToday: true,
  },
  {
    id: 'friend-3',
    nickname: '수학 탐험가 준호',
    representativeBadgeId: 'math-mental-calc-2',
    representativeBadgeEmoji: '🧮',
    representativeBadgeTitle: '머릿속에 계산기',
    studiedToday: false,
  },
  {
    id: 'friend-4',
    nickname: '창의왕 하은',
    representativeBadgeId: 'math-creative-2',
    representativeBadgeEmoji: '💡',
    representativeBadgeTitle: '문제 해결사',
    studiedToday: false,
  },
];

export const PRAISE_MESSAGES_MOCK: PraiseMessage[] = [
  {
    id: 'praise-1',
    senderName: '엄마',
    message: '민준아, 오늘도 수학 열심히 했구나! 엄마가 너무 자랑스러워 💕',
    emoji: '💕',
    createdAt: '2025-05-28T09:30:00',
    isNew: true,
  },
  {
    id: 'praise-2',
    senderName: '아빠',
    message: '7일 연속 학습 달성! 정말 대단해. 이번 주말에 맛있는 거 먹으러 가자! 🎉',
    emoji: '🎉',
    createdAt: '2025-05-27T20:15:00',
    isNew: true,
  },
  {
    id: 'praise-3',
    senderName: '엄마',
    message: '암산 뱃지 3단계 달성 축하해! 정말 열심히 했구나 🏆',
    emoji: '🏆',
    createdAt: '2025-05-25T18:00:00',
    isNew: false,
  },
];
